version: '3.8'

services:
  app:
    build: .
    container_name: referral-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  prometheus_data: 