global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'referral-app'
    static_configs:
      - targets: ['referral.acsfutureschool.com']
    metrics_path: '/api/metrics'
    scheme: https

  - job_name: 'prometheus'
    static_configs:
      - targets: ['referral-dashboard.acsfutureschool.com']
    metrics_path: '/'
    scheme: https