package models

import (
	"time"

	"github.com/google/uuid"
)

// ProductWishlist represents a single row from the `product_wishlist` table.
// The id column is a UUID generated by Postgres (gen_random_uuid()).
// All columns are NOT NULL in the DDL except id (default) and created_at (default).
// We use primitive types (not pointers) for mandatory fields so the JSON encoder
// omits `null` values gracefully.
//
// Note: The `products` themselves are returned via joins when required – see
// repository layer for details.
type ProductWishlist struct {
	ID        uuid.UUID `json:"id"`
	UserID    int       `json:"user_id"`
	ProductID int       `json:"product_id"`
	VariantID *int      `json:"variant_id,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// TableName tells any ORM / datastore helper the actual table name.
func (ProductWishlist) TableName() string { return "product_wishlist" }